spring:
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:sql/MINIBANK_ACCOUNT_DDL.sql
      data-locations: classpath:sql/MINIBANK_ACCOUNT_DML.sql
      encoding: UTF-8
  application:
    name: minibank-account
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: postgres
    password: admin1234
    url: jdbc:log4jdbc:postgresql://${POSTGRES}:5432/account
  #Spring Cloud Loadbalancer
  #TODO : Spring Cloud Loadbalancer 설정
  cloud:
    loadbalancer:      
      health-check:
        interval: 30s
      ribbon:
        enabled: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: 'true'
    path: /swagger-ui.html
  packages-to-scan: com.minibank.account.controller
mybatis:
  type-aliases-package: com.minibank.account.domain.entity
  mapper-locations: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: 'true'
#Customer API URL
#TODO: customer api url 수정
customer:
  api:
    url: http://${CUSTOMER}:8075/minibank/customer
server:
  servlet:
    context-path: /minibank/account
  port: '8075'
#### enviroment ####
#TODO: CUSTOMER service name 수정
CUSTOMER: minibank-customer
POSTGRES: localhost
EUREKA: localhost

#eureka
#TODO : Eureka 설정
eureka:
  client:
    service-url:
      defaultZone : http://${EUREKA}:8761/eureka
  instance:
    prefer-ip-address: true

#Resilience4j
#TODO : Resilience4j 설정
resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 5000 #최소 실패 지연시간에 대한 설정
        permittedNumberOfCallsInHalfOpenState: 4
        maxWaitDurationInHalfOpenState: 1000
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5 #실패 허용횟수에 대한 설정 이 횟수가 넘어가는 실패가 발생하면 fallback메소드가 호출된다.
        waitDurationInOpenState: 60000
    instances:
      customCircuitBreaker:
        baseConfig: default

#TODO: Openfeign
#openfeign setting
#connetion try timeout 설정 30초
#connetion read timeout(최대 작업 시간) 설정 30초
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000