spring:
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:sql/MINIBANK_ACCOUNT_DDL.sql
      data-locations: classpath:sql/MINIBANK_ACCOUNT_DML.sql
      encoding: UTF-8
  application:
    name: minibank-account
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: postgres
    password: admin1234
    url: jdbc:log4jdbc:postgresql://${POSTGRES}:5432/account
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: 'true'
    path: /swagger-ui.html
  packages-to-scan: com.minibank.account.controller
mybatis:
  type-aliases-package: com.minibank.account.domain.entity
  mapper-locations: classpath:sql/*.xml
  configuration:
    map-underscore-to-camel-case: 'true'
customer:
  api:
    url: http://${CUSTOMER}:8076/minibank/customer
POSTGRES: localhost
server:
  servlet:
    context-path: /minibank/account
  port: '8075'
CUSTOMER: localhost

#TODO: Resilience4j 설정#
